import { cargarProductos } from './Filters.js';

const STORAGE_KEY = 'userPreferences_v1';
const AUTO_KEY = 'prefs_auto_apply_v1';


const VIEWED_KEY = 'viewed_products_v1';
const MAX_VIEWED = 300;

function loadPreferences(){
  try{ const raw = localStorage.getItem(STORAGE_KEY); return raw ? JSON.parse(raw) : null; }catch(e){ console.error('Error parsing preferences', e); return null; }
}

function savePreferences(prefs){
  const out = Object.assign({}, prefs, { lastUpdated: Date.now(), autoGenerated: true });
  localStorage.setItem(STORAGE_KEY, JSON.stringify(out));
  try{ window.dispatchEvent(new CustomEvent('preferencesUpdated', { detail: out })); }catch(_){ }
}

function clearPreferences(){ localStorage.removeItem(STORAGE_KEY); }

function saveViewedProduct(prod){
  try{
    const raw = localStorage.getItem(VIEWED_KEY);
    const list = raw ? JSON.parse(raw) : [];
    // minimal representation
    const item = { id: prod.id, title: prod.title, category: prod.category || '', brand: prod.brand || '', ts: Date.now() };
    // remove previous with same id
    const filtered = list.filter(x => String(x.id) !== String(item.id));
    filtered.unshift(item);
    filtered.splice(MAX_VIEWED); // cap
    localStorage.setItem(VIEWED_KEY, JSON.stringify(filtered));
  }catch(e){ console.error('Error saving viewed', e); }
}

function readViewed(){
  try{ return JSON.parse(localStorage.getItem(VIEWED_KEY) || '[]'); }catch(e){ return []; }
}

function readCartSnapshot(){
  try{ return JSON.parse(localStorage.getItem('carrito') || '[]'); }catch(e){ return []; }
}

function topKeys(counts, topN=3){
  return Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,topN).map(x=>x[0]);
}

function extractFromText(text, keywords){
  const t = (text||'').toLowerCase();
  return keywords.filter(k => t.includes(k));
}

const KNOWN_COLORS = ['rosa','negro','blanco','azul','rojo','verde','amarillo','marron','gris','beige','nude','lila','purpura'];
const KNOWN_STYLES = ['boho','casual','formal','sport','vintage','minimal','street','elegante','urbano','retro'];

function inferPreferences(){
  const viewed = readViewed();
  const cart = readCartSnapshot();

  const categoryCounts = {};
  const colorCounts = {};
  const styleCounts = {};

  function inspect(prod){
    if(!prod) return;
    if(prod.category) categoryCounts[prod.category] = (categoryCounts[prod.category]||0)+1;
    const text = ((prod.title||'') + ' ' + (prod.description||'') + ' ' + (prod.brand||'')).toLowerCase();
    extractFromText(text, KNOWN_COLORS).forEach(c => colorCounts[c] = (colorCounts[c]||0)+1);
    extractFromText(text, KNOWN_STYLES).forEach(s => styleCounts[s] = (styleCounts[s]||0)+1);
  }

  viewed.forEach(v=>inspect(v));
  cart.forEach(c=>inspect(c));

  const prefs = {
    categories: topKeys(categoryCounts, 3),
    colors: topKeys(colorCounts, 3),
    styles: topKeys(styleCounts, 3)
  };

  return prefs;
}

let inferTimer = null;
function scheduleInferAndSave(delay = 800){
  if(inferTimer) clearTimeout(inferTimer);
  inferTimer = setTimeout(()=>{ const prefs = inferPreferences(); savePreferences(prefs); console.log('Preferences auto-saved:', prefs); }, delay);
}

window.addEventListener('productViewed', (e)=>{ try{ saveViewedProduct(e.detail); scheduleInferAndSave(); }catch(_){}});
window.addEventListener('cartUpdated', (e)=>{ try{ scheduleInferAndSave(); }catch(_){}});

function getAutoApplySetting(){ return localStorage.getItem(AUTO_KEY) === '1'; }
function setAutoApplySetting(enabled){
  localStorage.setItem(AUTO_KEY, enabled ? '1' : '0');
  try{ window.dispatchEvent(new CustomEvent('preferencesAutoApplyChanged', { detail:{ enabled } })); }catch(_){ }

  try{ const btn = document.getElementById('btn-apply-prefs'); if(btn) btn.disabled = !enabled; }catch(_){ }

  if(enabled){ try{ applyPreferencesNow(); }catch(e){ console.error('Error applying preferences immediately', e); } }
  else{ try{ cargarProductos(); }catch(e){ console.error('Error reverting to full catalog', e); } }
} 

async function applyPreferencesNow(){
  const prefs = loadPreferences();
  if(!prefs) return;
  if(prefs.categories && prefs.categories.length){
    const cat = prefs.categories[0];
    cargarProductos(`https://dummyjson.com/products/category/${encodeURIComponent(cat)}`);
    try{ window.dispatchEvent(new CustomEvent('preferencesAutoApplied', { detail: { method:'category', value:cat } })); }catch(_){ }
    return;
  }

  const qParts = [];
  if(prefs.colors) qParts.push(...prefs.colors);
  if(prefs.styles) qParts.push(...prefs.styles);
  if(qParts.length){
    const q = encodeURIComponent(qParts.join(' '));
    cargarProductos(`https://dummyjson.com/products/search?q=${q}`);
    try{ window.dispatchEvent(new CustomEvent('preferencesAutoApplied', { detail: { method:'search', value:qParts } })); }catch(_){ }
  }
}


window.addEventListener('preferencesUpdated', (e)=>{ try{ if(getAutoApplySetting()){ applyPreferencesNow(); } }catch(_){}});

export function initProfile(){

  scheduleInferAndSave(200);

  try{
    const toggle = document.getElementById('toggle-apply-prefs');
    const btnApply = document.getElementById('btn-apply-prefs');
    if(toggle){
      toggle.checked = getAutoApplySetting();

      if(btnApply) btnApply.disabled = !toggle.checked;
      toggle.addEventListener('change', (e)=>{ setAutoApplySetting(!!e.target.checked); if(btnApply) btnApply.disabled = !e.target.checked; });
    }
    if(btnApply){ btnApply.addEventListener('click', ()=>{ applyPreferencesNow(); }); }

    if(getAutoApplySetting()){
      setTimeout(()=>{ try{ applyPreferencesNow(); }catch(_){ } }, 400);
    }
  }catch(e){ console.error('Error wiring preferences UI', e); }
}

export { loadPreferences, savePreferences, clearPreferences, inferPreferences, scheduleInferAndSave, getAutoApplySetting, setAutoApplySetting, applyPreferencesNow };
